# This is a TOML document.
title = "TOML Example"

[database]
ports = [8000, 8001]
enabled = true
value = 42

[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

[[plugin]]
file = "fileA.toml"
number = 10

[[plugin]]
file = "fileB.toml"
number = 15
